"""Train and evaluate the optional learned CabinGuard etiology baseline.

The training data are synthetic SensorFrames generated by the existing
simulator. This proves the training/evaluation interface and learned model
contract; it is not clinical training or real-driver validation.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from cabinguard.classifier import BayesianEtiologyClassifier
from cabinguard.feature_extraction import FeatureExtractor
from cabinguard.learned_classifier import CLASS_NAMES, LearnedEtiologyClassifier
from cabinguard.simulator import MultimodalSensorSimulator, ScenarioType


SCENARIO_LABELS = {
    ScenarioType.NORMAL_DRIVING: "Normal",
    ScenarioType.CARDIAC_SYNCOPE: "Syncope",
    ScenarioType.EPILEPTIC_SEIZURE: "Seizure",
}


def collect_features(seeds: range) -> tuple[np.ndarray, np.ndarray]:
    rows: list[np.ndarray] = []
    labels: list[str] = []
    for seed in seeds:
        for scenario, label in SCENARIO_LABELS.items():
            extractor = FeatureExtractor()
            simulator = MultimodalSensorSimulator(scenario, duration_s=12.0, seed=seed)
            for index, frame in enumerate(simulator):
                if frame.timestamp < 7.0 or index % 10 != 0:
                    continue
                processed = extractor.process_frame(frame)
                rows.append(LearnedEtiologyClassifier.vectorize(processed))
                labels.append(label)
    return np.asarray(rows, dtype=float), np.asarray(labels)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=int, default=30)
    parser.add_argument("--model-path", type=Path, default=Path("models/etiology_logreg.joblib"))
    parser.add_argument("--metrics-path", type=Path, default=Path("results/learned_etiology_metrics.json"))
    args = parser.parse_args()
    if args.seeds < 4:
        raise ValueError("--seeds must be at least 4 for a train/test seed split")

    split = max(2, int(args.seeds * 0.8))
    train_x, train_y = collect_features(range(split))
    test_x, test_y = collect_features(range(split, args.seeds))

    learned = LearnedEtiologyClassifier().fit(train_x, train_y)
    classifier = learned.model
    predicted = classifier.predict(test_x)
    metrics = {
        "scope": "synthetic training and holdout only; not clinical evidence",
        "model": "StandardScaler + multinomial LogisticRegression",
        "feature_names": list(LearnedEtiologyClassifier.feature_names()),
        "train_samples": int(len(train_y)),
        "test_samples": int(len(test_y)),
        "accuracy": float(accuracy_score(test_y, predicted)),
        "labels": list(CLASS_NAMES),
        "confusion_matrix": confusion_matrix(test_y, predicted, labels=CLASS_NAMES).tolist(),
        "classification_report": classification_report(
            test_y, predicted, labels=CLASS_NAMES, output_dict=True, zero_division=0
        ),
        "train_seeds": split,
        "test_seeds": args.seeds - split,
        "baseline": "BayesianEtiologyClassifier remains the default safety classifier",
    }
    learned.save(args.model_path)
    args.metrics_path.parent.mkdir(parents=True, exist_ok=True)
    args.metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
